// @ts-check
// Plans and applies installer changes. planInstall / planUninstall only read;
// applyChanges is the only function that writes.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {
  MD_MARKERS, GITIGNORE_MARKERS, upsertMarked, removeMarked, mergeHooks, removeKitHooks, parseSettings,
} from './text.mjs';

/**
 * @typedef {{ path: string, action: 'create'|'update'|'unchanged'|'conflict'|'delete', content?: string, reason?: string, executable?: boolean, symlink?: boolean, pruneDirs?: string[] }} Change
 * A `conflict` with `content` replaces the file when accepted (install); one without
 * `content` deletes it when accepted (uninstall). A conflict with `symlink` is never
 * written or deleted. `executable` marks files written with mode 0o755. `pruneDirs`
 * (on the manifest delete) lists Kit-created directories to remove if left empty.
 */

export const MANIFEST = '.team/kit-manifest.json';
const SETTINGS = '.claude/settings.json';
const SETTINGS_BAK = '.claude/settings.json.bak';
const TEAM_JSON = '.team/team.json';
/** Files that may be created by the Kit and are deleted on uninstall only if they end up empty. */
const MERGED = ['CLAUDE.md', '.gitignore', SETTINGS];
const GITIGNORE_BODY = '.team/events*.jsonl\nagent-status.json\n.superpowers/';
/** Directories the Kit may create and may remove on uninstall, deepest first. */
const KIT_DIRS = ['.team/bin/cli', '.team/bin/hooks', '.team/bin/lib', '.team/bin', '.claude/agents', '.claude'];
const SYMLINK_REASON = 'is a symlink';

const SHIM = `#!/usr/bin/env node
// Generated by agent-team-kit: runs the team-status CLI.
import { main } from './cli/team-status.mjs';

process.exit(main(process.argv.slice(2), { cwd: process.cwd(), env: process.env }));
`;

/** Copied Kit files: [source relative to the kit, destination relative to the target, executable]. */
const COPIES = /** @type {const} */ ([
  ['agents/backend.md', '.claude/agents/backend.md', false],
  ['agents/frontend.md', '.claude/agents/frontend.md', false],
  ['agents/reviewer.md', '.claude/agents/reviewer.md', false],
  ['agents/tester.md', '.claude/agents/tester.md', false],
  ['cli/team-status.mjs', '.team/bin/cli/team-status.mjs', true],
  ['hooks/record.mjs', '.team/bin/hooks/record.mjs', true],
  ['lib/events.mjs', '.team/bin/lib/events.mjs', false],
  ['lib/paths.mjs', '.team/bin/lib/paths.mjs', false],
  ['templates/handoff-template.md', '.team/handoffs/handoff-template.md', false],
  ['planner/planner.md', '.team/planner.md', false],
  ['planner/work-order-template.md', '.team/work-order-template.md', false],
]);
const SHIM_PATH = '.team/bin/team-status.mjs';
/** The only paths a manifest may name; anything else in a manifest is ignored. */
const KIT_FILES = new Set([...COPIES.map(([, dest]) => dest), SHIM_PATH]);

/** @param {string} s */
export const sha256 = (s) => crypto.createHash('sha256').update(s, 'utf8').digest('hex');

/**
 * @param {string} dir
 * @param {string} rel POSIX relative path
 */
const abs = (dir, rel) => path.join(dir, ...rel.split('/'));

/**
 * True when `rel` or any directory between the target and it is a symlink.
 * @param {string} targetDir
 * @param {string} rel
 */
function hasSymlink(targetDir, rel) {
  const parts = rel.split('/');
  for (let i = 1; i <= parts.length; i++) {
    const st = fs.lstatSync(abs(targetDir, parts.slice(0, i).join('/')), { throwIfNoEntry: false });
    if (!st) return false;
    if (st.isSymbolicLink()) return true;
  }
  return false;
}

/** Paths that must not be symlinks at all: the Kit refuses to run rather than half-install. */
const MUST_NOT_LINK = ['.team/bin', MANIFEST, SETTINGS];

/**
 * Throw when the Kit's own folders, the manifest or settings.json are reached through a symlink.
 * @param {string} targetDir
 */
function refuseSymlinkedRoots(targetDir) {
  for (const rel of MUST_NOT_LINK) {
    const parts = rel.split('/');
    for (let i = 1; i <= parts.length; i++) {
      const sub = parts.slice(0, i).join('/');
      if (fs.lstatSync(abs(targetDir, sub), { throwIfNoEntry: false })?.isSymbolicLink()) {
        throw new Error(`${sub} is a symlink. The Kit will not write through symlinks, and installing only part of it would leave broken hooks. Replace ${sub} with a real ${i < parts.length ? 'folder' : 'file'}, then re-run; nothing was changed.`);
      }
    }
  }
}

/**
 * Fail loudly if `rel` is absolute, has a `..` segment, or resolves outside the target.
 * @param {string} targetDir
 * @param {string} rel
 */
function assertInside(targetDir, rel) {
  const root = path.resolve(targetDir);
  const full = path.resolve(root, rel);
  const back = path.relative(root, full);
  if (path.isAbsolute(rel) || rel.split(/[\\/]/).includes('..') || back === '' || back.startsWith('..') || path.isAbsolute(back)) {
    throw new Error(`Refusing to touch ${rel}: it is outside ${targetDir}.`);
  }
}

/**
 * @param {string} rel
 * @returns {Change}
 */
const symlinkConflict = (rel) => ({ path: rel, action: 'conflict', reason: SYMLINK_REASON, symlink: true });

/**
 * @param {string} file
 * @returns {string | null}
 */
function readOrNull(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch (e) {
    if (/** @type {NodeJS.ErrnoException} */ (e).code === 'ENOENT') return null;
    throw e;
  }
}

/** @param {Record<string, any>} v */
const settingsText = (v) => `${JSON.stringify(v, null, 2)}\n`;

/**
 * @param {string} rel
 * @param {string | null} current
 * @param {string} next
 * @returns {Change}
 */
function textChange(rel, current, next) {
  if (current === null) return { path: rel, action: 'create', content: next };
  if (current === next) return { path: rel, action: 'unchanged' };
  return { path: rel, action: 'update', content: next };
}

/**
 * @typedef {{ version?: string, files: Record<string, string>, created: string[], createdDirs: string[] }} Manifest
 */

/**
 * Read the manifest, keeping only entries the Kit can own (never `../` or absolute paths).
 * @param {string} targetDir
 * @returns {Manifest | null}
 */
function readManifest(targetDir) {
  const text = readOrNull(abs(targetDir, MANIFEST));
  if (text === null) return null;
  let m;
  try {
    m = JSON.parse(text);
  } catch {
    throw new Error(`${MANIFEST} is not valid JSON. Fix or delete it by hand, then re-run; nothing was changed.`);
  }
  const rawFiles = m && typeof m.files === 'object' && m.files && !Array.isArray(m.files) ? m.files : {};
  /** @type {Record<string, string>} */
  const files = {};
  for (const [rel, hash] of Object.entries(rawFiles)) {
    if (KIT_FILES.has(rel) && typeof hash === 'string') files[rel] = hash;
  }
  /** @param {unknown} list @param {string[]} allowed */
  const only = (list, allowed) => (Array.isArray(list) ? allowed.filter((x) => list.includes(x)) : []);
  return { version: m?.version, files, created: only(m?.created, MERGED), createdDirs: only(m?.createdDirs, KIT_DIRS) };
}

/**
 * @param {string} targetDir
 * @returns {{ text: string | null, settings: Record<string, any> }}
 */
function readSettings(targetDir) {
  const text = readOrNull(abs(targetDir, SETTINGS));
  const parsed = parseSettings(text);
  if (!parsed.ok) throw new Error(parsed.error);
  return { text, settings: parsed.settings };
}

/**
 * Work out every change an install would make. Reads only; throws (with a message
 * fit for the user) when the target cannot be changed safely.
 * @param {{ kitDir: string, targetDir: string }} opts
 * @returns {Change[]}
 */
export function planInstall({ kitDir, targetDir }) {
  refuseSymlinkedRoots(targetDir);
  const manifest = readManifest(targetDir);
  const version = JSON.parse(fs.readFileSync(path.join(kitDir, 'package.json'), 'utf8')).version;
  /** @type {Change[]} */
  const changes = [];
  /** @type {Record<string, string>} */
  const files = {};
  const linked = (/** @type {string} */ rel) => hasSymlink(targetDir, rel);

  /** @type {[string, string, boolean][]} */
  const sources = COPIES.map(([src, dest, exe]) => [fs.readFileSync(path.join(kitDir, ...src.split('/')), 'utf8'), dest, exe]);
  sources.push([SHIM, SHIM_PATH, true]);
  for (const [content, rel, executable] of sources) {
    const known = manifest?.files[rel];
    if (linked(rel)) {
      changes.push(symlinkConflict(rel));
      if (known !== undefined) files[rel] = known;
      continue;
    }
    const current = readOrNull(abs(targetDir, rel));
    /** @type {Change} */
    let c;
    if (current === null) c = { path: rel, action: 'create', content };
    else if (current === content) c = { path: rel, action: 'unchanged' };
    else if (known !== undefined && sha256(current) === known) c = { path: rel, action: 'update', content };
    else c = { path: rel, action: 'conflict', content, reason: known === undefined ? 'not written by the Kit' : 'customised since the last install' };
    if (executable) c.executable = true;
    // Conflicts are planned as kept; applyChanges records the new hash if one is replaced.
    if (c.action === 'conflict') {
      if (known !== undefined) files[rel] = known;
    } else {
      files[rel] = sha256(content);
    }
    changes.push(c);
  }

  const { text: settingsBefore, settings } = readSettings(targetDir);
  const merged = mergeHooks(settings, JSON.parse(fs.readFileSync(path.join(kitDir, 'templates', 'hooks.json'), 'utf8')));
  if (linked(SETTINGS)) {
    changes.push(symlinkConflict(SETTINGS));
  } else if (settingsBefore === null) {
    changes.push({ path: SETTINGS, action: 'create', content: settingsText(merged) });
  } else if (JSON.stringify(merged) !== JSON.stringify(settings)) {
    // Keep the first backup: it holds the user's own settings from before the Kit.
    if (!linked(SETTINGS_BAK) && readOrNull(abs(targetDir, SETTINGS_BAK)) === null) {
      changes.push({ path: SETTINGS_BAK, action: 'create', content: settingsBefore });
    }
    changes.push({ path: SETTINGS, action: 'update', content: settingsText(merged) });
  } else {
    changes.push({ path: SETTINGS, action: 'unchanged' });
  }

  const section = fs.readFileSync(path.join(kitDir, 'templates', 'claude-team-section.md'), 'utf8');
  for (const [rel, body, markers] of /** @type {const} */ ([['CLAUDE.md', section, MD_MARKERS], ['.gitignore', GITIGNORE_BODY, GITIGNORE_MARKERS]])) {
    const text = readOrNull(abs(targetDir, rel));
    const c = textChange(rel, text, upsertMarked(text ?? '', body, markers));
    // A symlinked file (e.g. CLAUDE.md -> AGENTS.md) is read but never written through.
    changes.push(c.action !== 'unchanged' && linked(rel) ? symlinkConflict(rel) : c);
  }

  if (linked(TEAM_JSON)) {
    changes.push(symlinkConflict(TEAM_JSON));
  } else if (readOrNull(abs(targetDir, TEAM_JSON)) === null) {
    const team = JSON.parse(fs.readFileSync(path.join(kitDir, 'templates', 'team.json'), 'utf8'));
    team.project = path.basename(path.resolve(targetDir));
    changes.push({ path: TEAM_JSON, action: 'create', content: `${JSON.stringify(team, null, 2)}\n` });
  } else {
    changes.push({ path: TEAM_JSON, action: 'unchanged' });
  }

  const created = manifest ? manifest.created : MERGED.filter((rel) => !fs.lstatSync(abs(targetDir, rel), { throwIfNoEntry: false }));
  const createdDirs = manifest ? manifest.createdDirs : KIT_DIRS.filter((rel) => !fs.lstatSync(abs(targetDir, rel), { throwIfNoEntry: false }));
  if (linked(MANIFEST)) {
    changes.push(symlinkConflict(MANIFEST));
  } else {
    changes.push(textChange(MANIFEST, readOrNull(abs(targetDir, MANIFEST)), manifestContent({ version, files, created, createdDirs })));
  }
  return changes;
}

/**
 * @param {{ version: string, files: Record<string, string>, created: string[], createdDirs: string[] }} m
 * @returns {string}
 */
function manifestContent({ version, files, created, createdDirs }) {
  const sorted = Object.fromEntries(Object.keys(files).sort().map((k) => [k, files[k]]));
  return `${JSON.stringify({ version, files: sorted, created, createdDirs }, null, 2)}\n`;
}

/**
 * Work out every change an uninstall would make. Reads only.
 * @param {{ targetDir: string }} opts
 * @returns {Change[]}
 */
export function planUninstall({ targetDir }) {
  refuseSymlinkedRoots(targetDir);
  const manifest = readManifest(targetDir);
  const created = manifest?.created ?? [];
  const linked = (/** @type {string} */ rel) => hasSymlink(targetDir, rel);
  /** @type {Change[]} */
  const changes = [];

  for (const [rel, hash] of Object.entries(manifest?.files ?? {})) {
    if (linked(rel)) { changes.push(symlinkConflict(rel)); continue; }
    const current = readOrNull(abs(targetDir, rel));
    if (current === null) continue;
    if (sha256(current) === hash) changes.push({ path: rel, action: 'delete' });
    else changes.push({ path: rel, action: 'conflict', reason: 'customised since the last install' });
  }

  if (linked(SETTINGS)) {
    changes.push(symlinkConflict(SETTINGS));
  } else {
    const { text: settingsBefore, settings } = readSettings(targetDir);
    if (settingsBefore !== null) {
      const after = removeKitHooks(settings);
      if (created.includes(SETTINGS) && Object.keys(after).length === 0) {
        changes.push({ path: SETTINGS, action: 'delete' });
      } else if (JSON.stringify(after) !== JSON.stringify(settings)) {
        changes.push({ path: SETTINGS, action: 'update', content: settingsText(after) });
      } else {
        changes.push({ path: SETTINGS, action: 'unchanged' });
      }
    }
  }

  for (const [rel, markers] of /** @type {const} */ ([['CLAUDE.md', MD_MARKERS], ['.gitignore', GITIGNORE_MARKERS]])) {
    const text = readOrNull(abs(targetDir, rel));
    if (text === null) continue;
    const after = removeMarked(text, markers);
    /** @type {Change} */
    const c = created.includes(rel) && after.trim() === '' ? { path: rel, action: 'delete' } : textChange(rel, text, after);
    changes.push(c.action !== 'unchanged' && linked(rel) ? symlinkConflict(rel) : c);
  }

  if (manifest) {
    if (linked(MANIFEST)) changes.push(symlinkConflict(MANIFEST));
    else changes.push({ path: MANIFEST, action: 'delete', pruneDirs: manifest.createdDirs });
  }
  return changes;
}

/**
 * @param {string} targetDir
 * @param {Change} c
 * @param {string} content
 */
function writeFile(targetDir, c, content) {
  assertInside(targetDir, c.path);
  if (hasSymlink(targetDir, c.path)) return; // never write through a symlink
  const full = abs(targetDir, c.path);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
  if (c.executable) fs.chmodSync(full, 0o755);
}

/**
 * @param {string} targetDir
 * @param {string} rel
 */
function removeFile(targetDir, rel) {
  assertInside(targetDir, rel);
  if (hasSymlink(targetDir, rel)) return; // never delete through a symlink
  fs.rmSync(abs(targetDir, rel), { force: true });
}

/**
 * Apply planned changes. Conflicts are asked about through resolveConflict
 * (true replaces on install, deletes on uninstall; false keeps the file).
 * Symlinked destinations are always skipped.
 * @param {Change[]} changes
 * @param {{ targetDir: string, resolveConflict: (c: Change) => boolean }} opts
 */
export function applyChanges(changes, { targetDir, resolveConflict }) {
  // Validate every path before touching anything.
  for (const c of changes) {
    assertInside(targetDir, c.path);
    for (const d of c.pruneDirs ?? []) assertInside(targetDir, d);
  }
  /** @type {Change | undefined} */
  let manifestChange;
  /** @type {Record<string, string>} */
  const replaced = {};
  /** @type {string[]} */
  let pruneDirs = [];

  for (const c of changes) {
    if (c.symlink || c.action === 'unchanged') continue;
    if (c.path === MANIFEST && c.action !== 'delete') { manifestChange = c; continue; }
    if (c.action === 'conflict') {
      if (!resolveConflict(c)) continue;
      if (c.content === undefined) {
        removeFile(targetDir, c.path);
      } else {
        writeFile(targetDir, c, c.content);
        replaced[c.path] = sha256(c.content);
      }
      continue;
    }
    if (c.action === 'delete') {
      removeFile(targetDir, c.path);
      if (c.pruneDirs) pruneDirs = c.pruneDirs;
      continue;
    }
    if (c.content === undefined) throw new Error(`Internal error: ${c.action} for ${c.path} has no content.`);
    writeFile(targetDir, c, c.content);
  }

  if (manifestChange) {
    const planned = manifestChange.content ?? readOrNull(abs(targetDir, MANIFEST));
    if (planned !== null) {
      const m = JSON.parse(planned);
      Object.assign(m.files, replaced);
      const next = manifestContent(m);
      if (readOrNull(abs(targetDir, MANIFEST)) !== next) writeFile(targetDir, manifestChange, next);
    }
  }

  // Remove only directories the Kit created, deepest first, and only when empty.
  for (const dir of KIT_DIRS.filter((d) => pruneDirs.includes(d))) {
    assertInside(targetDir, dir);
    if (hasSymlink(targetDir, dir)) continue;
    try {
      if (fs.readdirSync(abs(targetDir, dir)).length === 0) fs.rmdirSync(abs(targetDir, dir));
    } catch {
      // missing or unreadable: leave it
    }
  }
}
