// @ts-check
// Plans and applies installer changes. planInstall / planUninstall only read;
// applyChanges is the only function that writes.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {
  MD_MARKERS, GITIGNORE_MARKERS, upsertMarked, removeMarked, mergeHooks, removeKitHooks, parseSettings,
} from './text.mjs';

/**
 * @typedef {{ path: string, action: 'create'|'update'|'unchanged'|'conflict'|'delete', content?: string, reason?: string, executable?: boolean }} Change
 * A `conflict` with `content` replaces the file when accepted (install); one without
 * `content` deletes it when accepted (uninstall). `executable` marks files written with mode 0o755.
 */

export const MANIFEST = '.team/kit-manifest.json';
const SETTINGS = '.claude/settings.json';
const SETTINGS_BAK = '.claude/settings.json.bak';
const TEAM_JSON = '.team/team.json';
/** Files that may be created by the Kit and are deleted on uninstall only if they end up empty. */
const MERGED = ['CLAUDE.md', '.gitignore', SETTINGS];
const GITIGNORE_BODY = '.team/events*.jsonl\nagent-status.json\n.superpowers/';
/** Directories uninstall never removes, even when empty. */
const KEEP_DIRS = ['.team', '.team/handoffs'];

const SHIM = `#!/usr/bin/env node
// Generated by agent-team-kit: runs the team-status CLI.
import { main } from './cli/team-status.mjs';

process.exit(main(process.argv.slice(2), { cwd: process.cwd(), env: process.env }));
`;

/** Copied Kit files: [source relative to the kit, destination relative to the target, executable]. */
const COPIES = /** @type {const} */ ([
  ['agents/backend.md', '.claude/agents/backend.md', false],
  ['agents/frontend.md', '.claude/agents/frontend.md', false],
  ['agents/reviewer.md', '.claude/agents/reviewer.md', false],
  ['agents/tester.md', '.claude/agents/tester.md', false],
  ['cli/team-status.mjs', '.team/bin/cli/team-status.mjs', true],
  ['hooks/record.mjs', '.team/bin/hooks/record.mjs', true],
  ['lib/events.mjs', '.team/bin/lib/events.mjs', false],
  ['lib/paths.mjs', '.team/bin/lib/paths.mjs', false],
  ['templates/handoff-template.md', '.team/handoffs/handoff-template.md', false],
  ['planner/planner.md', '.team/planner.md', false],
  ['planner/work-order-template.md', '.team/work-order-template.md', false],
]);
const SHIM_PATH = '.team/bin/team-status.mjs';

/** @param {string} s */
export const sha256 = (s) => crypto.createHash('sha256').update(s, 'utf8').digest('hex');

/**
 * @param {string} dir
 * @param {string} rel POSIX relative path
 */
const abs = (dir, rel) => path.join(dir, ...rel.split('/'));

/**
 * @param {string} file
 * @returns {string | null}
 */
function readOrNull(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch (e) {
    if (/** @type {NodeJS.ErrnoException} */ (e).code === 'ENOENT') return null;
    throw e;
  }
}

/** @param {Record<string, any>} v */
const settingsText = (v) => `${JSON.stringify(v, null, 2)}\n`;

/**
 * @param {string} rel
 * @param {string | null} current
 * @param {string} next
 * @returns {Change}
 */
function textChange(rel, current, next) {
  if (current === null) return { path: rel, action: 'create', content: next };
  if (current === next) return { path: rel, action: 'unchanged' };
  return { path: rel, action: 'update', content: next };
}

/**
 * @param {string} targetDir
 * @returns {{ version?: string, files: Record<string, string>, created: string[] } | null}
 */
function readManifest(targetDir) {
  const text = readOrNull(abs(targetDir, MANIFEST));
  if (text === null) return null;
  let m;
  try {
    m = JSON.parse(text);
  } catch {
    throw new Error(`${MANIFEST} is not valid JSON. Fix or delete it by hand, then re-run; nothing was changed.`);
  }
  const files = m && typeof m.files === 'object' && m.files && !Array.isArray(m.files) ? m.files : {};
  const created = Array.isArray(m?.created) ? m.created.filter((/** @type {unknown} */ x) => typeof x === 'string') : [];
  return { version: m?.version, files, created };
}

/**
 * @param {string} targetDir
 * @returns {{ text: string | null, settings: Record<string, any> }}
 */
function readSettings(targetDir) {
  const text = readOrNull(abs(targetDir, SETTINGS));
  const parsed = parseSettings(text);
  if (!parsed.ok) throw new Error(parsed.error);
  return { text, settings: parsed.settings };
}

/**
 * Work out every change an install would make. Reads only; throws (with a message
 * fit for the user) when the target cannot be changed safely.
 * @param {{ kitDir: string, targetDir: string }} opts
 * @returns {Change[]}
 */
export function planInstall({ kitDir, targetDir }) {
  const manifest = readManifest(targetDir);
  const version = JSON.parse(fs.readFileSync(path.join(kitDir, 'package.json'), 'utf8')).version;
  /** @type {Change[]} */
  const changes = [];
  /** @type {Record<string, string>} */
  const files = {};

  /** @type {[string, string, boolean][]} */
  const sources = COPIES.map(([src, dest, exe]) => [fs.readFileSync(path.join(kitDir, ...src.split('/')), 'utf8'), dest, exe]);
  sources.push([SHIM, SHIM_PATH, true]);
  for (const [content, rel, executable] of sources) {
    const current = readOrNull(abs(targetDir, rel));
    const known = manifest?.files[rel];
    /** @type {Change} */
    let c;
    if (current === null) c = { path: rel, action: 'create', content };
    else if (current === content) c = { path: rel, action: 'unchanged' };
    else if (known !== undefined && sha256(current) === known) c = { path: rel, action: 'update', content };
    else c = { path: rel, action: 'conflict', content, reason: known === undefined ? 'not written by the Kit' : 'customised since the last install' };
    if (executable) c.executable = true;
    // Conflicts are planned as kept; applyChanges records the new hash if one is replaced.
    if (c.action === 'conflict') {
      if (known !== undefined) files[rel] = known;
    } else {
      files[rel] = sha256(content);
    }
    changes.push(c);
  }

  const { text: settingsBefore, settings } = readSettings(targetDir);
  const merged = mergeHooks(settings, JSON.parse(fs.readFileSync(path.join(kitDir, 'templates', 'hooks.json'), 'utf8')));
  if (settingsBefore === null) {
    changes.push({ path: SETTINGS, action: 'create', content: settingsText(merged) });
  } else if (JSON.stringify(merged) !== JSON.stringify(settings)) {
    const bak = readOrNull(abs(targetDir, SETTINGS_BAK));
    changes.push(textChange(SETTINGS_BAK, bak, settingsBefore));
    changes.push({ path: SETTINGS, action: 'update', content: settingsText(merged) });
  } else {
    changes.push({ path: SETTINGS, action: 'unchanged' });
  }

  const claudeMd = readOrNull(abs(targetDir, 'CLAUDE.md'));
  const section = fs.readFileSync(path.join(kitDir, 'templates', 'claude-team-section.md'), 'utf8');
  changes.push(textChange('CLAUDE.md', claudeMd, upsertMarked(claudeMd ?? '', section, MD_MARKERS)));
  const gitignore = readOrNull(abs(targetDir, '.gitignore'));
  changes.push(textChange('.gitignore', gitignore, upsertMarked(gitignore ?? '', GITIGNORE_BODY, GITIGNORE_MARKERS)));

  if (readOrNull(abs(targetDir, TEAM_JSON)) === null) {
    const team = JSON.parse(fs.readFileSync(path.join(kitDir, 'templates', 'team.json'), 'utf8'));
    team.project = path.basename(path.resolve(targetDir));
    changes.push({ path: TEAM_JSON, action: 'create', content: `${JSON.stringify(team, null, 2)}\n` });
  } else {
    changes.push({ path: TEAM_JSON, action: 'unchanged' });
  }

  const created = manifest
    ? manifest.created
    : MERGED.filter((rel) => readOrNull(abs(targetDir, rel)) === null);
  const manifestText = manifestContent({ version, files, created });
  changes.push(textChange(MANIFEST, readOrNull(abs(targetDir, MANIFEST)), manifestText));
  return changes;
}

/**
 * @param {{ version: string, files: Record<string, string>, created: string[] }} m
 * @returns {string}
 */
function manifestContent({ version, files, created }) {
  const sorted = Object.fromEntries(Object.keys(files).sort().map((k) => [k, files[k]]));
  return `${JSON.stringify({ version, files: sorted, created }, null, 2)}\n`;
}

/**
 * Work out every change an uninstall would make. Reads only.
 * @param {{ targetDir: string }} opts
 * @returns {Change[]}
 */
export function planUninstall({ targetDir }) {
  const manifest = readManifest(targetDir);
  const created = manifest?.created ?? [];
  /** @type {Change[]} */
  const changes = [];

  for (const [rel, hash] of Object.entries(manifest?.files ?? {})) {
    const current = readOrNull(abs(targetDir, rel));
    if (current === null) continue;
    if (sha256(current) === hash) changes.push({ path: rel, action: 'delete' });
    else changes.push({ path: rel, action: 'conflict', reason: 'customised since the last install' });
  }

  const { text: settingsBefore, settings } = readSettings(targetDir);
  if (settingsBefore !== null) {
    const after = removeKitHooks(settings);
    if (created.includes(SETTINGS) && Object.keys(after).length === 0) {
      changes.push({ path: SETTINGS, action: 'delete' });
    } else if (JSON.stringify(after) !== JSON.stringify(settings)) {
      changes.push({ path: SETTINGS, action: 'update', content: settingsText(after) });
    } else {
      changes.push({ path: SETTINGS, action: 'unchanged' });
    }
  }

  for (const [rel, markers] of /** @type {const} */ ([['CLAUDE.md', MD_MARKERS], ['.gitignore', GITIGNORE_MARKERS]])) {
    const text = readOrNull(abs(targetDir, rel));
    if (text === null) continue;
    const after = removeMarked(text, markers);
    if (created.includes(rel) && after.trim() === '') changes.push({ path: rel, action: 'delete' });
    else changes.push(textChange(rel, text, after));
  }

  if (manifest) changes.push({ path: MANIFEST, action: 'delete' });
  return changes;
}

/**
 * Remove empty directories from `rel`'s parent upwards, stopping at the target and at KEEP_DIRS.
 * @param {string} targetDir
 * @param {string} rel
 */
function pruneEmptyDirs(targetDir, rel) {
  let dir = path.posix.dirname(rel);
  while (dir !== '.' && !KEEP_DIRS.includes(dir)) {
    const full = abs(targetDir, dir);
    try {
      if (fs.readdirSync(full).length > 0) return;
      fs.rmdirSync(full);
    } catch {
      return;
    }
    dir = path.posix.dirname(dir);
  }
}

/**
 * @param {string} targetDir
 * @param {Change} c
 * @param {string} content
 */
function writeFile(targetDir, c, content) {
  const full = abs(targetDir, c.path);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
  if (c.executable) fs.chmodSync(full, 0o755);
}

/**
 * Apply planned changes. Conflicts are asked about through resolveConflict
 * (true replaces on install, deletes on uninstall; false keeps the file).
 * @param {Change[]} changes
 * @param {{ targetDir: string, resolveConflict: (c: Change) => boolean }} opts
 */
export function applyChanges(changes, { targetDir, resolveConflict }) {
  /** @type {Change | undefined} */
  let manifestChange;
  /** @type {Record<string, string>} */
  const replaced = {};
  /** @type {string[]} */
  const deleted = [];

  for (const c of changes) {
    if (c.path === MANIFEST && c.action !== 'delete') { manifestChange = c; continue; }
    if (c.action === 'unchanged') continue;
    if (c.action === 'conflict') {
      if (!resolveConflict(c)) continue;
      if (c.content === undefined) {
        fs.rmSync(abs(targetDir, c.path), { force: true });
        deleted.push(c.path);
      } else {
        writeFile(targetDir, c, c.content);
        replaced[c.path] = sha256(c.content);
      }
      continue;
    }
    if (c.action === 'delete') {
      fs.rmSync(abs(targetDir, c.path), { force: true });
      deleted.push(c.path);
      continue;
    }
    if (c.content === undefined) throw new Error(`Internal error: ${c.action} for ${c.path} has no content.`);
    writeFile(targetDir, c, c.content);
  }

  if (manifestChange) {
    const planned = manifestChange.content ?? readOrNull(abs(targetDir, MANIFEST));
    if (planned !== null) {
      const m = JSON.parse(planned);
      Object.assign(m.files, replaced);
      const next = manifestContent(m);
      if (readOrNull(abs(targetDir, MANIFEST)) !== next) writeFile(targetDir, manifestChange, next);
    }
  }

  for (const rel of deleted) pruneEmptyDirs(targetDir, rel);
}
